### ISSUE TITLE
Can we run parallel environments

### ISSUE THREAD

**Issue by harunuz** [BLG638-Project/final-2021#1]
Hi,

Does Symstar support parallelism?  Can we run experiments in parallel, maybe without rendering the environment?

**Comment by ferhatmelih** [comment]
Hi, 

There is information about running the simulation env withouth rendering in [here](https://github.com/BLG638-Project/final-2021/blob/main/environment.md).

About parallel execution, you can start SimStar at different ports with command 

    ./SimStar.sh -api-port=8085

and another one with 

    ./SimStar.sh -api-port=8086

Then when initilizing the environment, you can create it with different **port** arguments 

```
env1 = SimStarEnv(port=8085)
env2 = SimStarEnv(port=8086)
```python

**Comment by gulcinbaykal** [comment]
Hi,

We managed to use port 8080 and 8081 for parallel experiments. However, when we try to start the 3rd experiment using different ports such as 8082, 8083, 8085, 8086 etc., we obtained the following error:

`Traceback (most recent call last):
  File "train_example.py", line 233, in <module>
    train()
  File "train_example.py", line 69, in train
    env = SimstarEnv(track=TRACK_NAME,
  File "/home/gulcin/final-2021/sac_example/simstarEnv.py", line 73, in __init__
    all_roads = self.client.get_roads()
  File "/home/gulcin/.local/lib/python3.8/site-packages/simstar-2.0.1.-py3.8.egg/simstar/client.py", line 81, in get_roads
  File "/home/gulcin/anaconda3/envs/simstar-env/lib/python3.8/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/gulcin/anaconda3/envs/simstar-env/lib/python3.8/site-packages/msgpackrpc/session.py", line 51, in send_request
    self._transport.send_message([message.REQUEST, msgid, method, args])
AttributeError: 'NoneType' object has no attribute 'send_message'
Exception ignored in: <function SimstarEnv.__del__ at 0x7f93bf96d820>
Traceback (most recent call last):
  File "/home/gulcin/final-2021/sac_example/simstarEnv.py", line 378, in __del__
    self.client.set_sync_mode(False)
  File "/home/gulcin/.local/lib/python3.8/site-packages/simstar-2.0.1.-py3.8.egg/simstar/client.py", line 313, in set_sync_mode
  File "/home/gulcin/anaconda3/envs/simstar-env/lib/python3.8/site-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/home/gulcin/anaconda3/envs/simstar-env/lib/python3.8/site-packages/msgpackrpc/session.py", line 51, in send_request
    self._transport.send_message([message.REQUEST, msgid, method, args])
AttributeError: 'NoneType' object has no attribute 'send_message'`

Do you have any idea about what the problem and solution might be? Thanks in advance

**Comment by ferhatmelih** [comment]
maybe your computer resources are not enough to run all train codes in paralell. 

Can you check this please:
start simstar in no-render mode at some random port 8086

    ./SimStar.sh -api-port=8086 -nullrhi

then try to connect to it from 

   env = SimStarEnv(port=8086)

and see if it works. 
My guess is that your computer resources are not enough to run 3 trains in parallel . it is not about 8086 or a specific port

**Comment by gulcinbaykal** [comment]
It gave the same error in no-render mode either but it was related to resources, thank you
