### ISSUE TITLE
Environment crashes after a few episodes

### ISSUE THREAD

**Issue by BatuhanGencay** [BLG638-Project/final-2021#4]
I tried the new training code example with SimStar 2.0.1 but environment is crashing after a while. I tried a couple of times and it is still crashing after 4-5k steps. I add the error I got below.

`Traceback (most recent call last):
  File "train_example.py", line 220, in <module>
    train()
  File "train_example.py", line 105, in train
    obs = env.reset()
  File "/home/bg/Workspace/RL/final_project/simstarEnv.py", line 157, in reset
    opponent_sensor = new_agent.add_sensor(simstar.ESensorType.Distance, opponent_sensor_settings)
  File "/home/bg/.local/lib/python3.6/site-packages/simstar-2.0.1.-py3.6.egg/simstar/vehicle.py", line 57, in add_sensor
  File "/home/bg/.local/lib/python3.6/site-packages/simstar-2.0.1.-py3.6.egg/simstar/sensor.py", line 10, in __init__
  File "/home/bg/.local/lib/python3.6/site-packages/msgpackrpc/client.py", line 11, in __init__
    loop = loop or Loop()
  File "/home/bg/.local/lib/python3.6/site-packages/msgpackrpc/loop.py", line 13, in __init__
    self._ioloop = loop or ioloop.IOLoop()
  File "/home/bg/.local/lib/python3.6/site-packages/tornado/util.py", line 293, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/home/bg/.local/lib/python3.6/site-packages/tornado/platform/epoll.py", line 26, in initialize
    super(EPollIOLoop, self).initialize(impl=select.epoll(), **kwargs)
  File "/home/bg/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 709, in initialize
    self._waker = Waker()
  File "/home/bg/.local/lib/python3.6/site-packages/tornado/platform/posix.py", line 39, in __init__
    r, w = os.pipe()
OSError: [Errno 24] Too many open files`

**Comment by ferhatmelih** [comment]
did you re-install PythonAPI ? 

you can check by 

    pip show simstar

**Comment by ferhatmelih** [comment]
Also, I looked at the error and I have a guess on what the problem might be. 

checkout to this branch : [debug/issue-#4](https://github.com/BLG638-Project/final-2021/tree/debug/issue-%234)

and try again please. 

In case you change the environment, the code I added can be seen here: 
![image](https://user-images.githubusercontent.com/20578853/122909022-9ef5b000-d309-11eb-9b66-465daedc8460.png)

**Comment by BatuhanGencay** [comment]
this is the output of the `pip show simstar`:
`Name: simstar
Version: 2.0.1.
Summary: ADAS Simulator based on Unreal Engine
Home-page: UNKNOWN
Author: Eatron Technologies
Author-email: info@eatron.com
License: Proprietary
Location: /home/bg/.local/lib/python3.6/site-packages/simstar-2.0.1.-py3.6.egg
Requires: msgpack-rpc-python, numpy
Required-by: `

I am trying with that branch now

**Comment by BatuhanGencay** [comment]
I got a similar error with these changes

`Traceback (most recent call last):
  File "train_example.py", line 220, in <module>
  File "train_example.py", line 105, in train
  File "/home/bg/Workspace/RL/final_project/simstarEnv.py", line 129, in reset
  File "/home/bg/.local/lib/python3.6/site-packages/simstar-2.0.1.-py3.6.egg/simstar/vehicle.py", line 57, in add_sensor
  File "/home/bg/.local/lib/python3.6/site-packages/simstar-2.0.1.-py3.6.egg/simstar/sensor.py", line 10, in __init__
  File "/home/bg/.local/lib/python3.6/site-packages/msgpackrpc/client.py", line 11, in __init__
  File "/home/bg/.local/lib/python3.6/site-packages/msgpackrpc/loop.py", line 13, in __init__
  File "/home/bg/.local/lib/python3.6/site-packages/tornado/util.py", line 293, in __new__
  File "/home/bg/.local/lib/python3.6/site-packages/tornado/platform/epoll.py", line 26, in initialize
OSError: [Errno 24] Too many open files`

**Comment by ferhatmelih** [comment]
after how many episodes does this happen?

**Comment by BatuhanGencay** [comment]
50-100 episodes depending on the agent but number of steps are around 5k mostly

**Comment by ferhatmelih** [comment]
I made another update in the same branch. 
can you pull, and re-install simstar

  python setup.py install --user

**Comment by BatuhanGencay** [comment]
It seems OK now thank you
